### ISSUE TITLE
Wont compile on RPi3 Jessie had to add these

### ISSUE THREAD

**Issue by debsahu** [srcshelton/servoblaster#3]
` -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux` to `CPPFLAGS`

**Comment by srcshelton** [comment]
The supplied `Makefile` already does `CPPFLAGS ?= -I/opt/vc/include` (although note that this does allow your environment to override this definition - do you already have `CPPFLAGS` set?), and the code simply has `#include <bcm_host.h>`, which in turn contains:
```
#include "interface/vmcs_host/vc_dispmanx.h"
#include "interface/vmcs_host/vc_tvservice.h"
#include "interface/vmcs_host/vc_cec.h"
#include "interface/vmcs_host/vc_cecservice.h"
#include "interface/vmcs_host/vcgencmd.h"
```
... so I'd be surprised if these directories had to be explicitly referenced in your `CPPFLAGS`.

Could you paste the exact error that you're seeing?

I'll try to get my development Pi running again (I need to plug it into a screen - it's no longer raising Wifi) and confirm whether it still works for me... although I'll be on `stretch` rather than `jessie` (which *shouldn't* make a difference...)

**Comment by debsahu** [comment]
```
~/servoblaster $ make
cc -I/opt/vc/include -Wall -Wextra -g -O2 -o servod servod.c mailbox.c -L/opt/vc/lib -lm -lbcm_host
In file included from /opt/vc/include/interface/vcos/vcos_assert.h:149:0,
                from /opt/vc/include/interface/vcos/vcos.h:114,
                from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                from /opt/vc/include/bcm_host.h:50,
                from servod.c:45:
/opt/vc/include/interface/vcos/vcos_types.h:38:33: fatal error: vcos_platform_types.h: No such file or directory
#include "vcos_platform_types.h"
                              ^
compilation terminated.
Makefile:11: recipe for target 'servod' failed
make: *** [servod] Error 1
```

**Comment by srcshelton** [comment]
I can confirm that on a fully updated `stretch` system this does work - could you confirm that you've run '`sudo apt-get update ; sudo apt-get dist-upgrade`' and this still happens for you?

I'll try to download a `jessie` image tomorrow to see whether there's a discrepancy...

Could you run '`dpkg -l | grep libraspberrypi'` and paste the output here?  For reference, on `stretch` the current version is `1.20171029-1`.

**Comment by debsahu** [comment]
nevermind, I updated to stretch and dont have this issue anymore.
