### ISSUE TITLE
Timeout Error since upgrading to Stretch

### ISSUE THREAD

**Issue by hkeown** [srcshelton/servoblaster#4]
Dear Stuart,

Since upgrading to Stretch I've noticed the following errors `servoblaster.service: Failed with result 'timeout'`.

1. This is the clone I used - `sudo git clone https://github.com/srcshelton/servoblaster.git`

2. Compiled as - `sudo make install`

3. Added - `sudo nano /etc/init.d/servoblaster`:
```
# Use GPIO17,18, eliminate jitter
OPTS="--idle-timeout=2000 --p1pins=11,12 --max=235"
```

4. In `/var/log/syslog` - shows timeout errors:
```
Feb 27 11:12:27 raspberrypi systemd[1]: servoblaster.service: Start operation timed out. Terminating.
Feb 27 11:12:27 raspberrypi systemd[1]: Failed to start LSB: Start/stop servod..
Feb 27 11:12:27 raspberrypi systemd[1]: servoblaster.service: Unit entered failed state.
Feb 27 11:12:27 raspberrypi systemd[1]: servoblaster.service: Failed with result 'timeout'.
```

5. The output file is not created - `/dev/servoblaster-cfg`

6. Oddly enough, the commands move the servos

7. Output from servod:
```
Board model:                     2
GPIO configuration:             P1 (40 pins)
Using hardware:                PWM
Using DMA channel:              14
Idle timeout:             Disabled
Number of servos:                8
Servo cycle time:            20000us
Pulse increment step size:      10us
Minimum width value:            50 (500us)
Maximum width value:           250 (2500us)
Output levels:              Normal

Using P1 pins:                    7,11,12,13,15,16,18,22

Servo mapping:
     0 on P1-7               GPIO-4
     1 on P1-11              GPIO-17
     2 on P1-12              GPIO-18
     3 on P1-13              GPIO-27
     4 on P1-15              GPIO-22
     5 on P1-16              GPIO-23
     6 on P1-18              GPIO-24
     7 on P1-22              GPIO-25
```

8. `ps ax` produces:
```
  349 ?        S      0:00 /usr/local/sbin/servod --idle-timeout=2000 --p1pins=11,12 --max=235
 1695 pts/0    S+     0:00 grep --color=auto servod
```

Your expert opinion will be appreciated.

Harvey

**Comment by srcshelton** [comment]
Hi Harvey,

Because the `dev`directory *really* isn't the place for status files and the like, this version of `servoblaster` moves the default location for the status file to `/var/run/servoblaster.status` - although you're free to override this as you feel... the supplied init script temporarily uses `/tmp/servoblaster-status`, for example.

It looks as if `servoblaster` is actually just fine (as you mention, you can control your servos!), but the init script and/or systemd aren't interacting properly.

Looking at it, the (stock) init script isn't telling `servoblaster` to dæmonise, and so when systemd falls-back to the SysV init script, the process is started but systemd times-out waiting for it to return.

I'll push a fix for this ASAP, and take a look at providing a systemd unit file too.

Thanks for letting me know!

**Comment by hkeown** [comment]
Thank you so much for that quick response!

I’ll stick with your advice regarding file locations and will await your update. Let me know if here is any further debug info that you might require from my side.

Apologies for any inconvenience caused.

**Comment by srcshelton** [comment]
Not at all - my bad for not noticing this wasn't working!

(Although I thought my build-Pi was using the init script, so it's a little odd... entirely possible that I have local changes not added back to the repo).

I might struggle to find time to fix this properly before the end of the week, though - in the meantime, try either changing `/usr/local/sbin/servod $OPTS >/dev/null ` to `/usr/local/sbin/servod $OPTS >/dev/null &` or (better) changing `OPTS="--idle-timeout=2000"` to `OPTS="--idle-timeout=2000 --daemonise=1"` in `init.sysv`.

**Comment by hkeown** [comment]
(Additional report moved to Issue #5)
