### ISSUE TITLE
ServoBlaster on Raspberry Pi 3 Model B+

### ISSUE THREAD

**Issue by SinaJB** [srcshelton/servoblaster#6]
Hi
I have search and try every way to make ServoBlaster work on Raspberry Pi 3 Model B+ with Raspbian stretch but it didn't work (No movement on servo) please help me. there is any improved version? if not can you guide me how to make it work!!?

**Comment by srcshelton** [comment]
I can certainly try... but I'm afraid that I will need a little more information ;)

* Could you confirm that you are using this repo, rather than the original `richardghirst` parent this was forked from?
* Could you describe in detail what steps you have carried out, what input you've provided and what output you've seen?
* Finally, could you confirm your servo setup including how many servos you're attempting to drive and how they are powered?

I'd strongly recommend executing `servod` directly (with option `--daemonise=10`) rather than running it as a service whilst debugging, so that you can easily see any output produced.  You can also give `servod` the command `debug` to see what state it is in, and the separate `servodebug` can also be useful.

**Comment by SinaJB** [comment]
well i'm pretty beginner on this area and i'm sorry about that. i just install ServoBlaster on my raspberry and i have connected 2 servos on servo0 and servo1 (pin-7,14) and i have run command `echo 0=120 > /dev/servoblaster` or `echo 1=120 > /dev/servoblaster` and commands are executed without any error but it doesn't any movement on my servos. i want to use it for simple  pan tilt. if it possible to send me some commands to check or fix this? i have checked servos with

```
import RPi.GPIO as GPIO
from time import sleep
GPIO.setmode(GPIO.BOARD)
GPIO.setup(07, GPIO.OUT)
pwm=GPIO.PWM(07, 50)
pwm.start(0)
def SetAngle(angle):
	duty = angle / 18 + 2
	GPIO.output(07, True)
	pwm.ChangeDutyCycle(duty)
	sleep(1)
	GPIO.output(07, False)
	pwm.ChangeDutyCycle(0)
```
	
`>>> SetAngle(50)` seems worked
servos powered directly from raspberry

**Comment by srcshelton** [comment]
If you're running `servoblaster` as a service, you'll need to edit `/etc/init.d/servoblaster` to add `--p1pins=7,14` to the line beginning `OPTS=`.  If you're running manually, likewise ensure that the `--p1pins` parameter is set.

I'll close this issue for now (... it's been some time, sorry) but please feel free to re-open if this is still a problem!
